steps:
  - name: 'gcr.io/kaniko-project/executor'
    args:
      [
        '--dockerfile',
        './attestor/Dockerfile',
        '--context',
        './attestor',
        '--cache=true',
        '--destination=asia.gcr.io/$PROJECT_ID/$REPO_NAME/$BRANCH_NAME',
      ]
  - name: 'asia.gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'dynamic-attestation-mvp-$BRANCH_NAME',
        '--image=asia.gcr.io/$PROJECT_ID/$REPO_NAME/$BRANCH_NAME',
        '--region=asia-southeast1',
        '--port=80'
      ]
  - name: 'asia-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli'
    args:
      - -repo
      - 'asia.gcr.io/$PROJECT_ID/$REPO_NAME/$BRANCH_NAME'
      - -keep
      - '3'
      - -tag-filter-any
      - '.*'
